
on:
  push:
    branches: [staging]

name: Staging Deploy to Amazon ECS

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, lint, and test
        run: |
          npm ci
          # npm run lint
          npm audit
          # npm test
        env:
          CI: true
  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build docker image
        env:
          IMAGE_TAG: ${{ github.sha }}
          #ECR_REGISTRY: ${{steps.login-ecr.outputs.registry }}
          #ECR_REPOSITORY: happenings-repo
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker build -t "$GITHUB_REPOSITORY:$IMAGE_TAG" .
          # docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          # echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          


